apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mmo-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: mmo.local
      http:
        paths:
          # Authentication endpoints
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-app-svc
                port:
                  number: 8080

          # Game WebSocket endpoint
          - path: /ws/game
            pathType: Prefix
            backend:
              service:
                name: game-app-svc
                port:
                  number: 8080
