apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: default
type: Opaque
stringData:
  AUTH_POSTGRES_USER: postgres
  AUTH_POSTGRES_PASSWORD: postgres
  JWT_SECRET: verylongsecretkeyusedonlyforlocaldevelopment
