spring:
  application:
    name: game-service

  datasource:
    url: jdbc:postgresql://${GAME_POSTGRES_SVC}:5432/${GAME_POSTGRES_DB}
    username: ${GAME_POSTGRES_USER}
    password: ${GAME_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}

websocket:
  endpoint: ${WEBSOCKET_ENDPOINT}
  allowed-origins: "*"
